name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: move file
    - uses: actions/checkout@v3
      run: cp ./test-project/Dockerfile.move ./
    - name: build
      run: docker build . -f Dockerfile.move --tag test-act:latest
